from io import BytesIO
import datetime
from pathlib import Path

from sqlalchemy import select

from app.core import db
from app.tables import TimelineEvent

from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

PANDATA_LOGO_PATH = Path(__file__).resolve().parents[2] / "static" / "assets" / "logo" / "pandata-logo.png"

#
# Database utility functions
#
def _get_next_events(project_id):
    '''
    gets up to 5 events that happen after curent date
    '''
    today = datetime.date.today()
    events = db.session.scalars(
        select(TimelineEvent)
        .where(TimelineEvent.project_id == project_id)
        .order_by(TimelineEvent.start_date.asc())
    ).all()
    return [event for event in events if event.start_date.date() >= today][:5]

#
# Reportlab/papyrus style utilities
#
def _build_next_events_table(project, styles):
    rows = [["Event Title", "Type", "Date"]]

    for event in _get_next_events(project.id):
        rows.append([
            Paragraph(event.title or "", styles["BodyText"]),
            "Phase start" if event.end_date else "Event",
            event.start_date.strftime("%Y-%m-%d"),
        ])

    if len(rows) == 1:
        rows.append(["No upcoming events", "", ""])

    table = Table(rows, colWidths=[4.0 * inch, 1.25 * inch, 1.5 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("PADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return table


def _draw_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.HexColor("#555555"))
    text = "Generated by Pandata"
    logo_size = 0.18 * inch
    gap = 0.06 * inch
    text_width = canvas.stringWidth(text, "Helvetica", 9)
    total_width = text_width + gap + logo_size
    start_x = (doc.pagesize[0] - total_width) / 2
    footer_y = 0.5 * inch

    if PANDATA_LOGO_PATH.exists():
        canvas.drawImage(
            str(PANDATA_LOGO_PATH),
            start_x,
            footer_y - (logo_size / 2),
            width=logo_size,
            height=logo_size,
            preserveAspectRatio=True,
            mask="auto",
        )

    canvas.drawString(start_x + logo_size + gap, footer_y - 3, text)
    canvas.restoreState()

#
# Report generaton logic functions
#
def generate_report_pdf(project, generated_by):
    '''
    project: Project row from db
    generated_by: username (or eventually name) of person who
        generated the report on pandata
    '''
    generated_at = datetime.datetime.now().astimezone()

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=LETTER)
    styles = getSampleStyleSheet()
    lighter_text_style = styles["BodyText"].clone("ReportMeta")
    lighter_text_style.textColor = colors.HexColor("#555555")

    elements = [
        Paragraph(project.title or '', styles['Title']),
        Spacer(1, 0.22 * inch),
        Paragraph(
            f'Generated {generated_at.strftime("%Y-%m-%d %I:%M %p %Z")} by {generated_by}.',
            lighter_text_style,
        ),
        Paragraph(
            f'This report was automatically generated by Pandata based on the data that is available for Projet '
            f'"{project.title or ""}". Fresh reports can be generated at https://pandata.work',
            lighter_text_style,
        ),
        Spacer(1, 0.25 * inch),
        Paragraph('<b>Description:</b>', styles['BodyText']),
        Paragraph(project.description or 'No description provided.', styles['BodyText']),
        Spacer(1, 0.25 * inch),
        Paragraph('Upcoming Events', styles['Heading2']),
        Spacer(1, 0.1 * inch),
        _build_next_events_table(project, styles),
    ]

    doc.build(elements, onFirstPage=_draw_footer, onLaterPages=_draw_footer)
    buffer.seek(0)
    return buffer

def get_report_file_name(project_title):
    '''
    Builds filename for a report
    '''
    current = datetime.datetime.now()
    return f'report-{project_title}-{current.date()}.pdf'
